### ISSUE TITLE
input a grammar with multiple rules

### ISSUE THREAD

**Issue by imenjd** [BrunoRB/firstFollow#1]
**how to input a grammar with multiple rules?**
I tried concatenating the rules like this:
`var myGrammar = 'S -> b T'+ 'T -> A b'+ 'T -> B a'+ 'A -> a S'+ 'A -> C B'+ 'B -> b D'+ 'C -> c D'+ 'D -> null'+ 'D -> c D';`
but the output was this:  
first set
{ S: { b: 1 }, b: { b: 1 }, TT: { TT: 1 } }
follow set
{ S: { '$': 1 } }
which is abviously wrong, only the first rule is read.

I tried making the grammar one string , and still only read the first rule

**Comment by BrunoRB** [comment]
Hi!

You need to separate the rules with a new line **or** a semicolon, it's describe in the [rules](https://brunorb.github.io/firstFollow/): 
> Each set of rules must be in a newline and must not break into a new line, or optionally multiple sets of rules can be placed at the same line as long as all of them, with the exception of the last one, are terminated by a semicolon (;)

So what you want is something like this:

    var myGrammar = 'S -> b T ;' + 
		'T -> A b ;' + 
		'T -> B a ;' + 
		'A -> a S ;' + 
		'A -> C B ; ' + 
		'B -> b D ;' + 
		'C -> c D ;' + 
		'D -> null ;'+ 
		'D -> c D';

Which produces the following semicolon-delimited string:

    "S -> b T ;T -> A b ;T -> B a ;A -> a S ;A -> C B ; B -> b D ;C -> c D ;D -> null ;D -> c D"

Or 

    var myGrammar = "S -> b T \n" + 
		"T -> A b \n" +
		"T -> B a \n" +
		"A -> a S \n" +
		"A -> C B \n " +
		"B -> b D \n" +
		"C -> c D \n"+
		"D -> null \n"+
		"D -> c D";

That gives you a string with each rule in a new line:

    "S -> b T 
    T -> A b 
    T -> B a 
    A -> a S 
    A -> C B 
    B -> b D 
    C -> c D 
    D -> null 
    D -> c D"

**Comment by imenjd** [comment]
Thank you @BrunoRB !
